DISTANCE_TO_END_THRESHOLD = 50
STARTS_DISTANCE_CLUSTER_THRESHOLD = 5

MIN_COORDS_TO_CLUSTER_BY_CONNECTED_COMPONENTS = 60
COORD_FREQ_TRESHOLD = 6

NUMBER_OF_SIMULATIONS = 100
MAX_NUMBER_OF_COORDS = 400

CONNECTED_COMPONENTS_HAMMING_SIMILARITY_TRESHOLD = 0.6
CONNECTED_COMPONENTS_MAX_NUMBER_OF_READS = 20

MIN_READS_TO_FORM_PARTITION = 5
MAX_BAM_CSOFT_CLIP_TO_CLASSIFY_AS_RIGHT_READ = 30

MIN_DIATANCE_FROM_THE_BEGINNING_TO_CLASSIFY_AS_RIGHT_READ = 100
MIN_READ_ACCURACY = 0.85

MIN_EXTENSION_SIZE = 2000
MIN_COVERAGE_FOR_EXTENSION = 8
