DISTANCE_TO_END_THRESHOLD = 50
STARTS_DISTANCE_CLUSTER_THRESHOLD = 5

MIN_COORDS_TO_CLUSTER_BY_CONNECTED_COMPONENTS = 60
COORD_FREQ_TRESHOLD = 7

NUMBER_OF_SIMULATIONS = 50
MAX_NUMBER_OF_COORDS = 400

CONNECTED_COMPONENTS_HAMMING_SIMILARITY_TRESHOLD = 0.6
CONNECTED_COMPONENTS_MAX_NUMBER_OF_READS = 20

MIN_READS_TO_FORM_PARTITION = 4
MAX_DISTANCE_TO_JOIN_PARTITIONS = 5
DISTANCE_TO_FORM_FIRST_PARTITION = 20

MIN_READ_ACCURACY = 0.85

MIN_EXTENSION_SIZE = 1000
MIN_COVERAGE_FOR_EXTENSION = 8
